from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.scatter import RuleScatter
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AssistBattleAssets: 


	# Image Rule Assets
	# 好友界面前往协战界面 
	I_FRIENDS_GOTO_ASSIST_BATTLE = RuleImage(roi_front=(1205,539,40,72), roi_back=(1185,507,75,147), threshold=0.8, method="Template matching", file="./tasks/AssistBattle/ab/ab_friends_goto_assist_battle.png")
	# 现世勾协位置1 
	I_PRESENT_WORLD_JADE_ASSIST_1 = RuleImage(roi_front=(156,293,31,32), roi_back=(135,266,70,76), threshold=0.8, method="Template matching", file="./tasks/AssistBattle/ab/ab_present_world_jade_assist_1.png")
	# 现世勾协位置2 
	I_PRESENT_WORLD_JADE_ASSIST_2 = RuleImage(roi_front=(456,293,31,32), roi_back=(441,273,70,76), threshold=0.8, method="Template matching", file="./tasks/AssistBattle/ab/ab_present_world_jade_assist_2.png")
	# 现世勾协位置3 
	I_PRESENT_WORLD_JADE_ASSIST_3 = RuleImage(roi_front=(756,300,31,32), roi_back=(742,276,70,76), threshold=0.8, method="Template matching", file="./tasks/AssistBattle/ab/ab_present_world_jade_assist_3.png")


	# Ocr Rule Assets
	# 普通副本协战次数 
	O_NORMAL_ASSIST_COUNT = RuleOcr(roi=(875,160,66,34), area=(875,160,66,34), mode="DigitCounter", method="Default", keyword="", name="normal_assist_count")
	# 结界突破协战次数 
	O_REALMRAID_ASSIT_COUNT = RuleOcr(roi=(1078,203,49,37), area=(1078,203,49,37), mode="DigitCounter", method="Default", keyword="", name="realmraid_assit_count")


