from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LevelRushAssets: 


	# Click Rule Assets
	# 点击普通攻击 
	C_NORMAL_ATTACK_CLICK = RuleClick(roi_front=(992,632,72,75), roi_back=(992,632,72,75), name="normal_attack_click")
	# 点击进入上阵式神界面 
	C_CLICK_UP_ASSIST = RuleClick(roi_front=(275,452,252,142), roi_back=(275,452,252,142), name="click_up_assist")


	# Image Rule Assets
	# 点对话弹窗 
	I_DOT_DIALOG_POPUP = RuleImage(roi_front=(1253,300,16,16), roi_back=(0,102,1280,408), threshold=0.7, method="Template matching", file="./tasks/LevelRush/lr/lr_dot_dialog_popup.png")
	# 跳过对话 
	I_SKIP_TALK = RuleImage(roi_front=(841,558,57,27), roi_back=(841,558,57,27), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_skip_talk.png")
	# 指引折扇 
	I_GUIDE_FAN = RuleImage(roi_front=(1013,237,19,27), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_guide_fan.png")
	# 确认召唤 
	I_SUMMON_CONFIRM = RuleImage(roi_front=(418,620,173,51), roi_back=(418,620,173,51), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_summon_confirm.png")
	# 点击进入战斗 
	I_FIGHT = RuleImage(roi_front=(862,33,51,35), roi_back=(0,0,1280,549), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_fight.png")
	# 点击眼睛切换世界 
	I_OPEN_EYE = RuleImage(roi_front=(610,107,64,21), roi_back=(0,72,1280,402), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_open_eye.png")
	# 问号弹窗 
	I_QUESTION_POPUP = RuleImage(roi_front=(1269,231,11,36), roi_back=(0,72,1280,402), threshold=0.75, method="Template matching", file="./tasks/LevelRush/lr/lr_question_popup.png")
	# 跳过动画 
	I_MOVIE_SKIP = RuleImage(roi_front=(1192,42,41,34), roi_back=(1192,42,41,34), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_movie_skip.png")
	# 确认跳过 
	I_MOVIE_SKIP_CONFIRM = RuleImage(roi_front=(715,445,116,32), roi_back=(715,445,116,32), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_movie_skip_confirm.png")
	# 前往新手活动界面 
	I_GOTO_ROOKIE_ACT = RuleImage(roi_front=(207,308,38,37), roi_back=(109,173,364,274), threshold=0.7, method="Template matching", file="./tasks/LevelRush/lr/lr_goto_rookie_act.png")
	# 新手活动界面标志 
	I_CHECK_ROOKIE_ACT = RuleImage(roi_front=(88,17,160,39), roi_back=(88,17,160,39), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_check_rookie_act.png")
	# 手动模式 
	I_MANUAL_MODE = RuleImage(roi_front=(37,647,52,29), roi_back=(37,647,52,29), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_manual_mode.png")
	# 自动模式 
	I_AUTOMATIC_MODE = RuleImage(roi_front=(37,647,52,29), roi_back=(37,647,52,29), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_automatic_mode.png")
	# 单倍速 
	I_SINGLE_SPEED = RuleImage(roi_front=(107,602,39,26), roi_back=(107,602,39,26), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_single_speed.png")
	# 双倍速 
	I_DOUBLE_SPEED = RuleImage(roi_front=(107,602,39,26), roi_back=(107,602,39,26), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_double_speed.png")
	# 关闭个性化推荐弹窗 
	I_CLOSE_RECOMMEND = RuleImage(roi_front=(362,579,214,58), roi_back=(362,579,214,58), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_close_recommend.png")
	# 获取阴阳师弹窗 
	I_GET_ONMYOJI = RuleImage(roi_front=(259,112,30,22), roi_back=(226,82,79,211), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_get_onmyoji.png")
	# 红色关闭按钮 
	I_RED_CLOSE = RuleImage(roi_front=(1149,77,40,38), roi_back=(942,0,338,281), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_red_close.png")
	# 推荐协战式神 
	I_GH_BIRD_RECOMMEND = RuleImage(roi_front=(284,410,84,87), roi_back=(202,287,237,377), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_gh_bird_recommend.png")
	# 第一个借式神坑位 
	I_FIRST_BORROW = RuleImage(roi_front=(331,189,74,71), roi_back=(331,189,74,71), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_first_borrow.png")
	# 第一个坑位借到了姑获鸟 
	I_FIRST_BORROW_GET = RuleImage(roi_front=(331,189,74,71), roi_back=(331,189,74,71), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_first_borrow_get.png")
	# 黄色返回按钮 
	I_YELLOW_BACK_BUTTON = RuleImage(roi_front=(16,16,52,47), roi_back=(5,5,74,71), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_yellow_back_button.png")
	# 7级 
	I_LEVEK_7 = RuleImage(roi_front=(10,19,20,23), roi_back=(10,19,20,23), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_levek_7.png")
	# 锁剧情 
	I_LEVEL_LOCKED = RuleImage(roi_front=(370,342,28,25), roi_back=(287,156,857,344), threshold=0.6, method="Template matching", file="./tasks/LevelRush/lr/lr_level_locked.png")
	# 一键领取新手活动奖励 
	I_RECEIVE_ALL = RuleImage(roi_front=(1193,566,47,40), roi_back=(1193,566,47,40), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_receive_all.png")
	# 存在奖励标志 
	I_TASK_REWARD_EXIST = RuleImage(roi_front=(1240,144,18,16), roi_back=(128,78,1152,203), threshold=0.7, method="Template matching", file="./tasks/LevelRush/lr/lr_task_reward_exist.png")
	# 玩法介绍窗口 
	I_INTRODUCE_WINDOW = RuleImage(roi_front=(634,121,174,22), roi_back=(634,121,174,22), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_introduce_window.png")
	# 剧情抽卡界面 
	I_LR_CHECK_SUMMON = RuleImage(roi_front=(385,94,15,23), roi_back=(385,94,15,23), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_lr_check_summon.png")
	# 教学锁1 
	I_TECH_LOCK = RuleImage(roi_front=(863,381,285,72), roi_back=(863,381,285,72), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_tech_lock.png")
	# 点击妖怪1 
	I_CLICK_YOUKAI_1 = RuleImage(roi_front=(530,109,23,23), roi_back=(310,38,775,278), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_click_youkai_1.png")
	# 这里可以切换自动了 
	I_SWITCH_AUTOMATIC_MARK = RuleImage(roi_front=(294,32,20,22), roi_back=(294,32,20,22), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_switch_automatic_mark.png")
	# 点击回正视角 
	I_INIT_PERSPECTIVE = RuleImage(roi_front=(28,566,24,25), roi_back=(28,566,24,25), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_init_perspective.png")
	# 新手特权 
	I_ROOKIE_VIP = RuleImage(roi_front=(45,385,113,37), roi_back=(17,91,180,611), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_rookie_vip.png")
	# 新手特权页面内 
	I_IN_ROOKIE_VIP = RuleImage(roi_front=(45,303,113,35), roi_back=(17,91,180,611), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_in_rookie_vip.png")
	# 式神借用 
	I_BORROW_SHIKIGAMI = RuleImage(roi_front=(47,355,103,28), roi_back=(17,91,180,611), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_borrow_shikigami.png")
	# 式神借用页面内 
	I_IN_BORROW_SHIKIGAMI = RuleImage(roi_front=(47,355,103,28), roi_back=(17,91,180,611), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_in_borrow_shikigami.png")
	# 协战成功上阵 
	I_ASSIST_UP_SUCCESS = RuleImage(roi_front=(303,510,34,31), roi_back=(303,510,34,31), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_assist_up_success.png")
	# 交替页面检查 
	I_SWITCH_CHECK = RuleImage(roi_front=(21,534,31,63), roi_back=(21,534,31,63), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_switch_check.png")
	# 前往绑定 
	I_PHONE_BIND = RuleImage(roi_front=(976,460,70,75), roi_back=(976,460,70,75), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_phone_bind.png")
	# 取消绑定 
	I_PHONE_BIND_CANCEL = RuleImage(roi_front=(474,476,100,51), roi_back=(474,476,100,51), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_phone_bind_cancel.png")
	# 普通模式 
	I_NORMAL_MODE = RuleImage(roi_front=(986,601,108,44), roi_back=(986,601,108,44), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_normal_mode.png")
	# 困难模式 
	I_HARD_MODE = RuleImage(roi_front=(887,606,102,34), roi_back=(887,606,102,34), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_hard_mode.png")
	# 切换困难 
	I_TO_HARD = RuleImage(roi_front=(28,313,108,44), roi_back=(28,313,108,44), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_to_hard.png")
	# 最高章节 
	I_HIGHEST_CHAPTER = RuleImage(roi_front=(1067,457,25,27), roi_back=(1067,457,25,27), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_highest_chapter.png")
	# 跳过流程 
	I_SKIP_TO_30 = RuleImage(roi_front=(1181,621,53,53), roi_back=(1181,621,53,53), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_skip_to_30.png")
	# 跳过 
	I_LR_LEVEL_SKIP = RuleImage(roi_front=(704,456,173,67), roi_back=(704,456,173,67), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_lr_level_skip.png")
	# 同意未勾选状态 
	I_CHECK_AGREE = RuleImage(roi_front=(419,405,33,30), roi_back=(419,405,33,30), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_check_agree.png")
	# 同意勾选状态 
	I_CHECK_AGREE_DONE = RuleImage(roi_front=(419,405,33,30), roi_back=(419,405,33,30), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_check_agree_done.png")
	# 新手教学点击犬神 
	I_DOGGOD_CLICK = RuleImage(roi_front=(771,210,29,32), roi_back=(734,129,116,156), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_doggod_click.png")
	# 返回庭院 
	I_TOWN_BACK_MAIN = RuleImage(roi_front=(1039,233,32,63), roi_back=(989,199,129,273), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_town_back_main.png")
	# 第一天奖励 
	I_SIGN_REWARD_DAY1 = RuleImage(roi_front=(235,299,137,66), roi_back=(205,290,210,110), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_sign_reward_day1.png")
	# 未锁定阵容 
	I_TEAM_UNLOCK = RuleImage(roi_front=(1009,661,17,22), roi_back=(848,588,430,132), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_team_unlock.png")
	# 已锁定阵容 
	I_TEAM_LOCKED = RuleImage(roi_front=(1009,661,17,22), roi_back=(848,588,430,132), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_team_locked.png")
	# 花合战前往成就页面 
	I_DAILY_GOTO_ACHIEVEMENT = RuleImage(roi_front=(1086,651,44,34), roi_back=(1086,651,44,34), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_daily_goto_achievement.png")
	# 存在奖励 
	I_ACHIEVEMENT_REWARD_EXIST = RuleImage(roi_front=(255,169,31,31), roi_back=(250,79,41,563), threshold=0.9, method="Template matching", file="./tasks/LevelRush/lr/lr_achievement_reward_exist.png")
	# 检查成就页面 
	I_CHECK_ACHIEVEMENT = RuleImage(roi_front=(1185,621,62,47), roi_back=(1185,621,62,47), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_check_achievement.png")
	# 点击关闭成就子菜单 
	I_ACHIEVEMENT_MENU_CLOSE = RuleImage(roi_front=(251,153,31,31), roi_back=(250,79,41,563), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_achievement_menu_close.png")
	# 点击达摩领取成就奖励 
	I_GET_ACHIEVEMENT_REWARD = RuleImage(roi_front=(1079,173,33,38), roi_back=(1050,125,90,469), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_get_achievement_reward.png")
	# 杂货铺新手商店标志 
	I_SIDE_CHECK_ROOKIE_MALL = RuleImage(roi_front=(913,13,31,32), roi_back=(913,13,31,32), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_side_check_rookie_mall.png")
	# 前往新手商店 
	I_MALL_GOTO_ROOKIE_MALL = RuleImage(roi_front=(877,651,45,32), roi_back=(877,651,45,32), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_mall_goto_rookie_mall.png")
	# 超值体力礼盒 
	I_ROOKIE_SUSHI_GIFT = RuleImage(roi_front=(226,161,64,69), roi_back=(226,161,64,69), threshold=0.9, method="Template matching", file="./tasks/LevelRush/lr/lr_rookie_sushi_gift.png")
	# 超值体力礼盒购买 
	I_BUY_SUSHI_GIFT = RuleImage(roi_front=(596,498,41,48), roi_back=(596,498,41,48), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_buy_sushi_gift.png")
	# 经验妖怪创建按钮 
	I_EXP_YOUKAI_CREATE = RuleImage(roi_front=(604,495,70,39), roi_back=(604,495,70,39), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_exp_youkai_create.png")
	# 七级前先不跳过剧情 
	I_CANCEL_BEFORE_7 = RuleImage(roi_front=(416,475,130,36), roi_back=(416,475,130,36), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_cancel_before_7.png")
	# 新手商店前往特殊商店 
	I_ROOKIE_GOTO_SPECIAL = RuleImage(roi_front=(1187,298,44,67), roi_back=(1169,90,85,488), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_rookie_goto_special.png")
	# 点击前往权限设置子页面 
	I_GOTO_PERMISSION = RuleImage(roi_front=(1168,333,29,67), roi_back=(1168,333,29,67), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_goto_permission.png")
	# 推送权限 
	I_PUSH_PERMISSION = RuleImage(roi_front=(100,82,53,67), roi_back=(100,82,53,67), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_push_permission.png")
	# 领取推送奖励50勾玉 
	I_GET_PUSH_REWARD = RuleImage(roi_front=(561,501,169,58), roi_back=(561,501,169,58), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_get_push_reward.png")
	# 前往添加好友界面 
	I_FRIEND_GOTO_ADD = RuleImage(roi_front=(1196,280,55,102), roi_back=(1196,280,55,102), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_friend_goto_add.png")
	# 一键绑定 
	I_BIND_BUTTON = RuleImage(roi_front=(976,597,146,36), roi_back=(976,597,146,36), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_bind_button.png")
	# 未获取绑定奖励 
	I_BIND_REWARD_EXSIT = RuleImage(roi_front=(684,596,30,40), roi_back=(684,596,30,40), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_bind_reward_exsit.png")
	# 设备获取通讯录权限确定按钮 
	I_DEVICE_PERMISSION_CONFIRM = RuleImage(roi_front=(669,383,174,51), roi_back=(669,383,174,51), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_device_permission_confirm.png")
	# 添加好友页面标志 
	I_CHECK_ADD = RuleImage(roi_front=(94,640,32,56), roi_back=(94,640,32,56), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_check_add.png")
	# 已领取推送奖励 
	I_PUSH_REWARD_ALREADY_GET = RuleImage(roi_front=(561,501,169,58), roi_back=(561,501,169,58), threshold=0.8, method="Template matching", file="./tasks/LevelRush/lr/lr_push_reward_already_get.png")


	# Ocr Rule Assets
	# 点击任意位置继续 
	O_CLICK_ANYWHERE_CONTINUE = RuleOcr(roi=(544,459,186,36), area=(365,438,530,87), mode="Single", method="Default", keyword="点击任意位置继续", name="click_anywhere_continue")
	# 点击空白处关闭 
	O_CLICK_BLANK_CLOSE = RuleOcr(roi=(552,658,186,36), area=(374,620,530,87), mode="Single", method="Default", keyword="点击空白处关闭", name="click_blank_close")
	# 当前等级 
	O_CURRENT_LEVEL = RuleOcr(roi=(0,19,47,25), area=(0,5,52,87), mode="Digit", method="Default", keyword="", name="current_level")
	# 当前章节 
	O_CURRENT_CHAPTER = RuleOcr(roi=(1057,452,121,40), area=(1057,450,215,103), mode="Single", method="Default", keyword="", name="current_chapter")
	# 当前体力较低的情况 
	O_CURRENT_SUSHI_LOW = RuleOcr(roi=(881,0,181,53), area=(881,0,181,53), mode="Single", method="Default", keyword="", name="current_sushi_low")


	# Swipe Rule Assets
	# 抽卡 
	S_SUMMON_SWIPE = RuleSwipe(roi_front=(668,445,32,40), roi_back=(666,275,35,51), mode="default", name="summon_swipe")
	# 上阵协战式神 
	S_BORROW_SHIKIGAMI_UP = RuleSwipe(roi_front=(273,550,93,94), roi_back=(582,344,100,100), mode="default", name="borrow_shikigami_up")


