from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityExplorationAssets: 


	# Image Rule Assets
	# 活动探索界面检查标志 
	I_CHECK_ACT_EXPLORATION = RuleImage(roi_front=(544,16,185,27), roi_back=(526,0,223,54), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_check_act_exploration.png")
	# 主线 
	I_MAIN_EVENT = RuleImage(roi_front=(28,115,48,20), roi_back=(28,115,48,20), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_main_event.png")
	# 战斗事件 
	I_FIGHT_EVENT = RuleImage(roi_front=(1069,26,33,28), roi_back=(1003,0,277,81), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_fight_event.png")
	# 获得新助战式神 
	I_GET_ASSIST = RuleImage(roi_front=(877,126,42,35), roi_back=(877,126,42,35), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_get_assist.png")
	# 宝箱事件 
	I_BOX_EVENT = RuleImage(roi_front=(537,95,214,22), roi_back=(537,95,214,22), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_box_event.png")
	# 遭遇战 
	I_ENCOUNTER_BATTLE = RuleImage(roi_front=(27,293,64,24), roi_back=(23,94,83,360), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_encounter_battle.png")
	# 支线 
	I_BRANCH_EVENT = RuleImage(roi_front=(27,203,49,20), roi_back=(23,94,83,360), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_branch_event.png")
	# 活动弹窗关闭按钮 
	I_ACT_RED_CLOSE = RuleImage(roi_front=(1202,137,41,42), roi_back=(1202,137,41,42), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_act_red_close.png")
	# 确认跳过 
	I_ACT_CONFIRM_SKIP = RuleImage(roi_front=(720,445,112,34), roi_back=(666,425,215,71), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_act_confirm_skip.png")
	# 活动剧情锁定 
	I_ACT_LOCKED = RuleImage(roi_front=(256,111,21,23), roi_back=(245,97,39,84), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_act_locked.png")
	# 活动页面跳转活动探索剧情页面 
	I_ACT_GOTO_ACT_EXPLORATION = RuleImage(roi_front=(1038,330,73,119), roi_back=(1038,330,73,119), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_act_goto_act_exploration.png")
	# 跳过剧情 
	I_ACT_SKIP = RuleImage(roi_front=(1157,36,53,25), roi_back=(1135,15,102,71), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_act_skip.png")
	# 遭遇战战斗界面识别 
	I_ENCOUNTER_BATTLE_EVENT = RuleImage(roi_front=(809,82,107,32), roi_back=(809,82,107,32), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_encounter_battle_event.png")
	# 返回庭院 
	I_BACK_TO_MAIN = RuleImage(roi_front=(77,20,43,37), roi_back=(0,1,256,79), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_back_to_main.png")
	#  
	I_HARD_FIGHT_CLOSE = RuleImage(roi_front=(1096,114,41,41), roi_back=(1096,114,41,41), threshold=0.8, method="Template matching", file="./tasks/ActivityExploration/ae/ae_hard_fight_close.png")


	# Ocr Rule Assets
	# 点击挑战 
	O_ACT_CHALLENGE = RuleOcr(roi=(1048,540,97,53), area=(1000,492,204,136), mode="Single", method="Default", keyword="挑战", name="act_challenge")
	# 点击开启 
	O_ACT_OPEN = RuleOcr(roi=(1052,554,97,54), area=(1000,492,204,136), mode="Single", method="Default", keyword="开启", name="act_open")


	# Swipe Rule Assets
	# 活动界面向下滑动 
	S_SWIPE_DOWN = RuleSwipe(roi_front=(208,167,21,21), roi_back=(208,104,21,21), mode="vector", name="swipe_down")


