from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.scatter import RuleScatter
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FrogChallengeAssets: 


	# Image Rule Assets
	# 前往青蛙瓷器挑战赛 
	I_GOTO_FROG_CHALLENGE = RuleImage(roi_front=(1183,376,45,28), roi_back=(1166,113,88,404), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/fc/fc_goto_frog_challenge.png")
	# 首次进入跳过 
	I_FC_SKIP = RuleImage(roi_front=(1157,32,53,29), roi_back=(1129,17,105,63), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/fc/fc_fc_skip.png")
	# 青蛙瓷器挑战赛页面标志 
	I_CHECK_FROG_CHALLENGE = RuleImage(roi_front=(1080,19,27,26), roi_back=(1065,7,62,52), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/fc/fc_check_frog_challenge.png")
	# 战斗 
	I_FC_FIRE = RuleImage(roi_front=(1159,641,64,28), roi_back=(1121,571,141,126), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/fc/fc_fc_fire.png")
	# 无奖励战斗就停止 
	I_FC_FIRE_STOP = RuleImage(roi_front=(1159,641,64,28), roi_back=(1121,571,141,126), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/fc/fc_fc_fire_stop.png")


	# Ocr Rule Assets
	# 神秘骰子奖励进度 
	O_MYSTERY_DICE_REWARD = RuleOcr(roi=(1117,257,98,31), area=(1117,257,98,31), mode="DigitCounter", method="Default", keyword="", name="mystery_dice_reward")
	# 点击任意位置继续 
	O_CLICK_ANYWHERE_CONTINUE = RuleOcr(roi=(548,460,185,31), area=(548,460,185,31), mode="Single", method="Default", keyword="", name="click_anywhere_continue")


